"""
IDF Generator — Translates building model into EnergyPlus IDF file.

Ported from egc-platform/idf_generator.py for Claude Desktop skill.
Takes BuildingCollector output and generates valid EnergyPlus input files.
"""

import math
import json
import os
import copy
from typing import List, Dict, Any, Optional


def ft_to_m(ft: float) -> float:
    """Convert feet to meters."""
    return ft * 0.3048


def btu_to_w(btu: float) -> float:
    """Convert BTU/h to Watts."""
    return btu * 0.293071


def r_to_rsi(r_ip: float) -> float:
    """Convert R-value (IP) to RSI (m²·K/W)."""
    return r_ip * 0.176110


def u_ip_to_si(u_ip: float) -> float:
    """Convert U-factor (IP: Btu/h·ft²·°F) to SI (W/m²·K)."""
    return u_ip * 5.678263


def f_to_c(f: float) -> float:
    """Convert Fahrenheit to Celsius."""
    return (f - 32) * 5 / 9


def cfm_to_m3s(cfm: float) -> float:
    """Convert CFM to m³/s."""
    return cfm * 0.000471947


def sqft_to_m2(sqft: float) -> float:
    """Convert square feet to square meters."""
    return sqft * 0.092903


class IDFGenerator:
    """Generate EnergyPlus IDF files from building model data."""

    def __init__(self, payload: Dict[str, Any]):
        """
        Initialize generator with building model payload.

        Args:
            payload: Building model dict with keys:
                - project: {name, climate_zone, building_type, units, north_axis}
                - stories: [{name, floor_to_floor, floor_to_ceiling, spaces: [...]}]
                - constructions: [{name, wall_type, wall_r_value, roof_r_value, ...}]
                - window_defs: [{name, wwr, u_factor, shgc, vlt}]
                - hvac_equipment: [{name, equipment_type, capacity_btuh, ...}]
                - thermal_zones: [{name, heating_setpoint, cooling_setpoint, ...}]
        """
        self.project = payload.get('project', {})
        self.stories = payload.get('stories', [])
        self.constructions = payload.get('constructions', [])
        self.window_defs = payload.get('window_defs', [])
        self.hvac_equipment = payload.get('hvac_equipment', [])
        self.thermal_zones = payload.get('thermal_zones', [])
        self.lines: List[str] = []
        self.zone_names: List[str] = []
        self.zone_floor_areas: Dict[str, float] = {}  # zone_name -> m²

    def add(self, text: str):
        """Add raw IDF text."""
        self.lines.append(text)

    def add_comment(self, text: str):
        """Add a comment line."""
        self.lines.append(f"! {text}")

    def generate(self) -> str:
        """Generate the complete IDF string."""
        self._add_header()
        self._add_simulation_control()
        self._add_building()
        self._add_timestep()
        self._add_run_period()
        self._add_ground_temperatures()
        self._add_schedules()
        self._add_materials_and_constructions()
        self._add_zones_and_geometry()
        self._add_fenestration()
        self._add_internal_loads()
        self._add_hvac()
        self._add_output_variables()
        return "\n".join(self.lines)

    def _add_header(self):
        """Add IDF header with project metadata."""
        self.add_comment("=" * 70)
        self.add_comment(f"  Audette EGC Platform — EnergyPlus Model")
        self.add_comment(f"  Project: {self.project.get('name', 'Untitled')}")
        self.add_comment(f"  Climate Zone: {self.project.get('climate_zone', 'N/A')}")
        self.add_comment(f"  Building Type: {self.project.get('building_type', 'N/A')}")
        self.add_comment(f"  Generated by Audette EGC Platform")
        self.add_comment("=" * 70)
        self.add("")

    def _add_simulation_control(self):
        """Add Version and SimulationControl objects."""
        self.add("Version,24.1;")
        self.add("")
        self.add("SimulationControl,")
        self.add("  No,                      !- Do Zone Sizing Calculation")
        self.add("  No,                      !- Do System Sizing Calculation")
        self.add("  No,                      !- Do Plant Sizing Calculation")
        self.add("  Yes,                     !- Run Simulation for Sizing Periods")
        self.add("  Yes;                     !- Run Simulation for Weather File Run Periods")
        self.add("")

    def _add_building(self):
        """Add Building object."""
        name = self.project.get('name', 'Building')
        north = self.project.get('north_axis', 0)
        self.add(f"Building,")
        self.add(f"  {name},                  !- Name")
        self.add(f"  {north},                 !- North Axis (deg)")
        self.add(f"  City,                    !- Terrain")
        self.add(f"  0.04,                    !- Loads Convergence Tolerance Value")
        self.add(f"  0.4,                     !- Temperature Convergence Tolerance Value (deltaC)")
        self.add(f"  FullExterior,            !- Solar Distribution")
        self.add(f"  25,                      !- Maximum Number of Warmup Days")
        self.add(f"  6;                       !- Minimum Number of Warmup Days")
        self.add("")

    def _add_timestep(self):
        """Add Timestep object."""
        self.add("Timestep,6;")
        self.add("")

    def _add_run_period(self):
        """Add RunPeriod object for annual simulation."""
        self.add("RunPeriod,")
        self.add("  Annual,                  !- Name")
        self.add("  1,                       !- Begin Month")
        self.add("  1,                       !- Begin Day of Month")
        self.add("  ,                        !- Begin Year")
        self.add("  12,                      !- End Month")
        self.add("  31,                      !- End Day of Month")
        self.add("  ,                        !- End Year")
        self.add("  Sunday,                  !- Day of Week for Start Day")
        self.add("  No,                      !- Use Weather File Holidays and Special Days")
        self.add("  No,                      !- Use Weather File Daylight Saving Period")
        self.add("  No,                      !- Apply Weekend Holiday Rule")
        self.add("  Yes,                     !- Use Weather File Rain Indicators")
        self.add("  Yes;                     !- Use Weather File Snow Indicators")
        self.add("")

    def _add_ground_temperatures(self):
        """Add Site:GroundTemperature:BuildingSurface with climate-appropriate values."""
        # Monthly ground temps in Celsius, varies by climate zone
        cz = self.project.get('climate_zone', '5A')

        if cz.startswith('5'):
            # Zone 5 (Cool-Humid, Midwest)
            temps = "3.5, 2.5, 4.0, 7.5, 13.0, 17.5, 20.0, 20.5, 18.0, 13.5, 8.5, 5.0"
        elif cz.startswith('4'):
            # Zone 4 (Mixed-Humid, Mid-Atlantic)
            temps = "7.0, 5.5, 7.0, 10.5, 16.0, 20.5, 23.0, 23.5, 21.0, 16.5, 11.5, 8.0"
        elif cz.startswith('3'):
            # Zone 3 (Warm-Humid, Southeast)
            temps = "10.0, 9.0, 10.5, 13.5, 18.0, 22.5, 25.0, 25.5, 23.0, 18.5, 13.5, 10.5"
        elif cz.startswith('2'):
            # Zone 2 (Hot-Humid, Gulf Coast)
            temps = "15.0, 14.0, 15.0, 17.5, 21.5, 25.0, 27.0, 27.5, 25.5, 22.0, 18.0, 15.5"
        elif cz.startswith('1'):
            # Zone 1 (Very Hot-Humid, South Florida)
            temps = "20.0, 19.5, 20.0, 21.5, 24.0, 26.5, 28.0, 28.5, 27.0, 24.5, 22.0, 20.5"
        elif cz.startswith('6'):
            # Zone 6 (Cold-Humid, Northern states)
            temps = "0.5, -0.5, 1.0, 5.0, 10.5, 15.0, 17.5, 18.0, 15.5, 11.0, 6.0, 2.5"
        elif cz.startswith('7') or cz.startswith('8'):
            # Zone 7/8 (Very Cold, Subarctic)
            temps = "-3.0, -4.0, -2.0, 2.0, 7.5, 12.0, 14.5, 15.0, 12.5, 8.0, 3.0, -1.0"
        else:
            # Default to Zone 5
            temps = "3.5, 2.5, 4.0, 7.5, 13.0, 17.5, 20.0, 20.5, 18.0, 13.5, 8.5, 5.0"

        self.add("Site:GroundTemperature:BuildingSurface,")
        self.add(f"  {temps};")
        self.add("")

    def _add_schedules(self):
        """Add all schedules for the building."""
        self.add_comment("--- Schedules ---")
        self.add("")

        # Schedule type limits
        self.add("ScheduleTypeLimits,")
        self.add("  Any Number;              !- Name")
        self.add("")
        self.add("ScheduleTypeLimits,")
        self.add("  Fraction,                !- Name")
        self.add("  0,                       !- Lower Limit Value")
        self.add("  1,                       !- Upper Limit Value")
        self.add("  Continuous;              !- Numeric Type")
        self.add("")
        self.add("ScheduleTypeLimits,")
        self.add("  Temperature,             !- Name")
        self.add("  -100,                    !- Lower Limit Value")
        self.add("  200,                     !- Upper Limit Value")
        self.add("  Continuous;              !- Numeric Type")
        self.add("")

        # Always On/Off
        self.add("Schedule:Constant,Always On,Fraction,1.0;")
        self.add("Schedule:Constant,Always Off,Fraction,0.0;")
        self.add("")

        # Activity level schedule for People objects (120 W = ~410 Btu/h sedentary metabolic rate)
        self.add("Schedule:Constant,ActivitySchedule,Any Number,120;")
        self.add("")

        # Thermostat control type schedule (4 = DualSetpoint)
        self.add("Schedule:Constant,DualSetpointControlType,Any Number,4;")
        self.add("")

        # Residential occupancy schedule (multifamily)
        self.add("Schedule:Compact,")
        self.add("  ResOccupancy,            !- Name")
        self.add("  Fraction,                !- Schedule Type Limits Name")
        self.add("  Through: 12/31,          !- Field 1")
        self.add("  For: Weekdays,           !- Field 2")
        self.add("  Until: 07:00, 1.0,       !- Field 3-4")
        self.add("  Until: 09:00, 0.5,       !- Field 5-6")
        self.add("  Until: 17:00, 0.25,      !- Field 7-8")
        self.add("  Until: 20:00, 0.5,       !- Field 9-10")
        self.add("  Until: 24:00, 1.0,       !- Field 11-12")
        self.add("  For: Weekends Holidays,  !- Field 13")
        self.add("  Until: 09:00, 1.0,       !- Field 14-15")
        self.add("  Until: 17:00, 0.75,      !- Field 16-17")
        self.add("  Until: 24:00, 1.0,       !- Field 18-19")
        self.add("  For: AllOtherDays,       !- Field 20")
        self.add("  Until: 24:00, 0.5;       !- Field 21-22")
        self.add("")

        # Lighting schedule
        self.add("Schedule:Compact,")
        self.add("  ResLighting,             !- Name")
        self.add("  Fraction,                !- Schedule Type Limits Name")
        self.add("  Through: 12/31,          !- Field 1")
        self.add("  For: Weekdays,           !- Field 2")
        self.add("  Until: 06:00, 0.1,       !- Field 3-4")
        self.add("  Until: 08:00, 0.5,       !- Field 5-6")
        self.add("  Until: 18:00, 0.2,       !- Field 7-8")
        self.add("  Until: 22:00, 0.8,       !- Field 9-10")
        self.add("  Until: 24:00, 0.3,       !- Field 11-12")
        self.add("  For: Weekends Holidays,  !- Field 13")
        self.add("  Until: 08:00, 0.1,       !- Field 14-15")
        self.add("  Until: 22:00, 0.6,       !- Field 16-17")
        self.add("  Until: 24:00, 0.3,       !- Field 18-19")
        self.add("  For: AllOtherDays,       !- Field 20")
        self.add("  Until: 24:00, 0.2;       !- Field 21-22")
        self.add("")

        # Equipment (plug loads) schedule
        self.add("Schedule:Compact,")
        self.add("  ResEquipment,            !- Name")
        self.add("  Fraction,                !- Schedule Type Limits Name")
        self.add("  Through: 12/31,          !- Field 1")
        self.add("  For: AllDays,            !- Field 2")
        self.add("  Until: 06:00, 0.4,       !- Field 3-4")
        self.add("  Until: 08:00, 0.7,       !- Field 5-6")
        self.add("  Until: 18:00, 0.5,       !- Field 7-8")
        self.add("  Until: 22:00, 0.9,       !- Field 9-10")
        self.add("  Until: 24:00, 0.5;       !- Field 11-12")
        self.add("")

        # Heating/cooling thermostat schedules
        htg_sp = 21.1  # 70°F default
        clg_sp = 23.9  # 75°F default
        if self.thermal_zones:
            htg_sp = f_to_c(self.thermal_zones[0].get('heating_setpoint', 70))
            clg_sp = f_to_c(self.thermal_zones[0].get('cooling_setpoint', 75))

        self.add(f"Schedule:Constant,HtgSetpoint,Temperature,{htg_sp:.1f};")
        self.add(f"Schedule:Constant,ClgSetpoint,Temperature,{clg_sp:.1f};")
        self.add("")

        # DHW schedule
        self.add("Schedule:Compact,")
        self.add("  DHW Schedule,            !- Name")
        self.add("  Fraction,                !- Schedule Type Limits Name")
        self.add("  Through: 12/31,          !- Field 1")
        self.add("  For: AllDays,            !- Field 2")
        self.add("  Until: 06:00, 0.15,      !- Field 3-4")
        self.add("  Until: 08:00, 0.70,      !- Field 5-6")
        self.add("  Until: 12:00, 0.30,      !- Field 7-8")
        self.add("  Until: 14:00, 0.15,      !- Field 9-10")
        self.add("  Until: 18:00, 0.30,      !- Field 11-12")
        self.add("  Until: 21:00, 0.55,      !- Field 13-14")
        self.add("  Until: 24:00, 0.25;      !- Field 15-16")
        self.add("")

        # DHW temperature schedules
        self.add("Schedule:Constant,DHW Target Temp,Temperature,60.0;")
        self.add("  !- 60°C = 140°F hot water delivery temp")
        self.add("Schedule:Constant,DHW Inlet Temp,Temperature,10.0;")
        self.add("  !- 10°C = 50°F cold water mains (varies by location)")
        self.add("")

    def _add_materials_and_constructions(self):
        """Add materials and constructions for envelope components."""
        self.add_comment("--- Materials & Constructions ---")
        self.add("")

        # For each construction in the model, create materials + construction
        for i, const in enumerate(self.constructions):
            wall_r = const.get('wall_r_value', 13)
            wall_ci = const.get('wall_ci_r_value', 0)
            roof_r = const.get('roof_r_value', 20)
            slab_r = const.get('slab_r_value', 0)
            wall_type = const.get('wall_type', 'mass')
            name = const.get('name', f'Construction_{i}')
            safe_name = name.replace(' ', '_').replace('-', '_')

            # Wall construction
            self._add_wall_construction(safe_name, wall_type, wall_r, wall_ci)
            # Roof construction
            self._add_roof_construction(safe_name, roof_r)
            # Floor construction
            self._add_floor_construction(safe_name, slab_r)

        # If no constructions defined, add defaults
        if not self.constructions:
            self._add_wall_construction("Default", "mass", 4.0, 0)
            self._add_roof_construction("Default", 10.0)
            self._add_floor_construction("Default", 0)

        # Interior constructions
        self._add_interior_constructions()

    def _add_wall_construction(self, prefix: str, wall_type: str, r_cavity: float, r_ci: float):
        """Create wall material layers and construction."""
        # Outer layer
        if wall_type == 'mass':
            self.add(f"Material,")
            self.add(f"  {prefix}_WallOuter,      !- Name")
            self.add(f"  MediumRough,             !- Roughness")
            self.add(f"  0.1016,                  !- Thickness (m) [4 in brick]")
            self.add(f"  0.89,                    !- Conductivity (W/m-K)")
            self.add(f"  1920,                    !- Density (kg/m3)")
            self.add(f"  790;                     !- Specific Heat (J/kg-K)")
            self.add("")
        else:  # steel_frame, wood_frame, metal_building
            self.add(f"Material,")
            self.add(f"  {prefix}_WallOuter,      !- Name")
            self.add(f"  MediumSmooth,            !- Roughness")
            self.add(f"  0.0127,                  !- Thickness (m) [0.5 in]")
            self.add(f"  0.16,                    !- Conductivity (W/m-K)")
            self.add(f"  784,                     !- Density (kg/m3)")
            self.add(f"  830;                     !- Specific Heat (J/kg-K)")
            self.add("")

        # Insulation layer — use R-value to compute thickness
        total_r_si = r_to_rsi(r_cavity + r_ci)
        if total_r_si < 0.1:
            total_r_si = 0.1  # minimum
        ins_conductivity = 0.04  # typical fiberglass/foam
        ins_thickness = total_r_si * ins_conductivity
        ins_thickness = max(0.01, min(0.5, ins_thickness))  # clamp

        self.add(f"Material,")
        self.add(f"  {prefix}_WallInsulation, !- Name")
        self.add(f"  MediumRough,             !- Roughness")
        self.add(f"  {ins_thickness:.4f},       !- Thickness (m)")
        self.add(f"  {ins_conductivity},        !- Conductivity (W/m-K)")
        self.add(f"  32,                       !- Density (kg/m3)")
        self.add(f"  830;                      !- Specific Heat (J/kg-K)")
        self.add("")

        # Inner layer (gypsum)
        self.add(f"Material,")
        self.add(f"  {prefix}_WallInner,      !- Name")
        self.add(f"  MediumSmooth,            !- Roughness")
        self.add(f"  0.0159,                  !- Thickness (m) [5/8 in gypsum]")
        self.add(f"  0.16,                    !- Conductivity (W/m-K)")
        self.add(f"  784,                     !- Density (kg/m3)")
        self.add(f"  830;                     !- Specific Heat (J/kg-K)")
        self.add("")

        # Wall construction
        self.add(f"Construction,")
        self.add(f"  {prefix}_Wall,           !- Name")
        self.add(f"  {prefix}_WallOuter,      !- Outside Layer")
        self.add(f"  {prefix}_WallInsulation, !- Layer 2")
        self.add(f"  {prefix}_WallInner;      !- Layer 3")
        self.add("")

    def _add_roof_construction(self, prefix: str, roof_r: float):
        """Create roof material layers and construction."""
        # Roof membrane
        self.add(f"Material,")
        self.add(f"  {prefix}_RoofMembrane,   !- Name")
        self.add(f"  VeryRough,               !- Roughness")
        self.add(f"  0.0095,                  !- Thickness (m)")
        self.add(f"  0.16,                    !- Conductivity (W/m-K)")
        self.add(f"  1121,                    !- Density (kg/m3)")
        self.add(f"  1460;                    !- Specific Heat (J/kg-K)")
        self.add("")

        # Roof insulation
        r_si = r_to_rsi(roof_r)
        if r_si < 0.1:
            r_si = 0.1
        ins_k = 0.04
        ins_t = r_si * ins_k
        ins_t = max(0.01, min(1.0, ins_t))

        self.add(f"Material,")
        self.add(f"  {prefix}_RoofInsulation, !- Name")
        self.add(f"  MediumRough,             !- Roughness")
        self.add(f"  {ins_t:.4f},              !- Thickness (m)")
        self.add(f"  {ins_k},                  !- Conductivity (W/m-K)")
        self.add(f"  32,                       !- Density (kg/m3)")
        self.add(f"  830;                      !- Specific Heat (J/kg-K)")
        self.add("")

        # Roof deck (concrete)
        self.add(f"Material,")
        self.add(f"  {prefix}_RoofDeck,       !- Name")
        self.add(f"  MediumRough,             !- Roughness")
        self.add(f"  0.1524,                  !- Thickness (m) [6 in concrete]")
        self.add(f"  1.311,                   !- Conductivity (W/m-K)")
        self.add(f"  2240,                    !- Density (kg/m3)")
        self.add(f"  900;                     !- Specific Heat (J/kg-K)")
        self.add("")

        self.add(f"Construction,")
        self.add(f"  {prefix}_Roof,           !- Name")
        self.add(f"  {prefix}_RoofMembrane,   !- Outside Layer")
        self.add(f"  {prefix}_RoofInsulation, !- Layer 2")
        self.add(f"  {prefix}_RoofDeck;       !- Layer 3")
        self.add("")

    def _add_floor_construction(self, prefix: str, slab_r: float):
        """Create floor construction."""
        # Concrete slab
        self.add(f"Material,")
        self.add(f"  {prefix}_Slab,           !- Name")
        self.add(f"  MediumRough,             !- Roughness")
        self.add(f"  0.2032,                  !- Thickness (m) [8 in concrete]")
        self.add(f"  1.311,                   !- Conductivity (W/m-K)")
        self.add(f"  2240,                    !- Density (kg/m3)")
        self.add(f"  900;                     !- Specific Heat (J/kg-K)")
        self.add("")

        if slab_r > 0:
            r_si = r_to_rsi(slab_r)
            ins_t = r_si * 0.04
            ins_t = max(0.01, min(0.5, ins_t))
            self.add(f"Material,")
            self.add(f"  {prefix}_SlabInsulation, !- Name")
            self.add(f"  MediumRough,             !- Roughness")
            self.add(f"  {ins_t:.4f},              !- Thickness (m)")
            self.add(f"  0.04,                    !- Conductivity (W/m-K)")
            self.add(f"  32,                       !- Density (kg/m3)")
            self.add(f"  830;                      !- Specific Heat (J/kg-K)")
            self.add("")
            self.add(f"Construction,")
            self.add(f"  {prefix}_Floor,          !- Name")
            self.add(f"  {prefix}_Slab,           !- Outside Layer")
            self.add(f"  {prefix}_SlabInsulation; !- Layer 2")
        else:
            self.add(f"Construction,")
            self.add(f"  {prefix}_Floor,          !- Name")
            self.add(f"  {prefix}_Slab;           !- Outside Layer")
        self.add("")

    def _add_interior_constructions(self):
        """Add interior wall and floor constructions."""
        self.add(f"Material,")
        self.add(f"  IntGypsum,               !- Name")
        self.add(f"  MediumSmooth,            !- Roughness")
        self.add(f"  0.0159,                  !- Thickness (m)")
        self.add(f"  0.16,                    !- Conductivity (W/m-K)")
        self.add(f"  784,                     !- Density (kg/m3)")
        self.add(f"  830;                     !- Specific Heat (J/kg-K)")
        self.add("")
        self.add("Construction,")
        self.add("  InteriorWall,            !- Name")
        self.add("  IntGypsum,               !- Outside Layer")
        self.add("  IntGypsum;               !- Layer 2")
        self.add("")
        self.add("Construction,")
        self.add("  InteriorFloor,           !- Name")
        self.add("  IntGypsum;               !- Layer 1")
        self.add("")

        # Window construction (simple glazing)
        if self.window_defs:
            wd = self.window_defs[0]
            u_si = u_ip_to_si(wd.get('u_factor', 0.42))
            shgc = wd.get('shgc', 0.40)
            vlt = wd.get('vlt', 0.50)
        else:
            u_si = u_ip_to_si(1.0)  # single pane default
            shgc = 0.70
            vlt = 0.70

        self.add(f"WindowMaterial:SimpleGlazingSystem,")
        self.add(f"  SimpleWindow,            !- Name")
        self.add(f"  {u_si:.3f},               !- U-Factor (W/m2-K)")
        self.add(f"  {shgc};                   !- Solar Heat Gain Coefficient")
        self.add("")
        self.add("Construction,")
        self.add("  WindowConstruction,      !- Name")
        self.add("  SimpleWindow;            !- Outside Layer")
        self.add("")

    def _add_zones_and_geometry(self):
        """Add thermal zones and building surfaces from stories/spaces."""
        if not self.stories:
            return

        self.add_comment("--- Zones & Geometry ---")
        self.add("")
        self.add("GlobalGeometryRules,")
        self.add("  UpperLeftCorner,         !- Starting Vertex Position")
        self.add("  CounterClockWise,        !- Vertex Entry Direction")
        self.add("  Relative;               !- Coordinate System")
        self.add("")

        # Get construction prefix for referencing materials
        const_prefix = "Default"
        if self.constructions:
            const_prefix = self.constructions[0].get('name', 'Default').replace(' ', '_').replace('-', '_')

        # Track cumulative height for stacking stories
        cum_height_ft = 0.0
        num_stories = len(self.stories)

        for si, story in enumerate(self.stories):
            ftf = story.get('floor_to_floor', 10)
            ftc = story.get('floor_to_ceiling', 9)
            floor_z_m = ft_to_m(cum_height_ft)
            ceil_z_m = ft_to_m(cum_height_ft + ftc)

            is_ground = (si == 0)
            is_top = (si == num_stories - 1)

            for sp in story.get('spaces', []):
                space_name = sp.get('name', f'Space_{si}')
                zone_name = f"{space_name}".replace(' ', '_')
                self.zone_names.append(zone_name)

                # Calculate floor area in m²
                verts = sp.get('vertices', [])
                area_ft2 = self._polygon_area(verts)
                area_m2 = sqft_to_m2(area_ft2)
                self.zone_floor_areas[zone_name] = area_m2

                # Zone object
                self.add(f"Zone,")
                self.add(f"  {zone_name},              !- Name")
                self.add(f"  0,                        !- Direction of Relative North (deg)")
                self.add(f"  0,                        !- X Origin (m)")
                self.add(f"  0,                        !- Y Origin (m)")
                self.add(f"  {floor_z_m:.3f},           !- Z Origin (m)")
                self.add(f"  ,                         !- Type")
                self.add(f"  1,                        !- Multiplier")
                self.add(f"  autocalculate,            !- Ceiling Height (m)")
                self.add(f"  autocalculate;            !- Volume (m3)")
                self.add("")

                # Build surfaces from vertices
                verts_m = [[ft_to_m(v[0]), ft_to_m(v[1])] for v in verts]
                n_verts = len(verts_m)
                if n_verts < 3:
                    continue

                # Floor surface
                self.add(f"BuildingSurface:Detailed,")
                self.add(f"  {zone_name}_Floor,        !- Name")
                self.add(f"  Floor,                    !- Surface Type")
                if is_ground:
                    self.add(f"  {const_prefix}_Floor,    !- Construction Name")
                    self.add(f"  {zone_name},              !- Zone Name")
                    self.add(f"  ,                         !- Space Name")
                    self.add(f"  Ground,                   !- Outside Boundary Condition")
                    self.add(f"  ,                         !- Outside Boundary Condition Object")
                else:
                    self.add(f"  InteriorFloor,            !- Construction Name")
                    self.add(f"  {zone_name},              !- Zone Name")
                    self.add(f"  ,                         !- Space Name")
                    self.add(f"  Adiabatic,                !- Outside Boundary Condition")
                    self.add(f"  ,                         !- Outside Boundary Condition Object")
                self.add(f"  NoSun,                    !- Sun Exposure")
                self.add(f"  NoWind,                   !- Wind Exposure")
                self.add(f"  ,                         !- View Factor to Ground")
                self.add(f"  {n_verts},                !- Number of Vertices")
                # Floor vertices (counterclockwise when looking down = clockwise from outside)
                for vi in range(n_verts):
                    v = verts_m[vi]
                    comma = "," if vi < n_verts - 1 else ";"
                    self.add(f"  {v[0]:.3f}, {v[1]:.3f}, 0.000{comma}")
                self.add("")

                # Ceiling/Roof surface
                self.add(f"BuildingSurface:Detailed,")
                self.add(f"  {zone_name}_Ceiling,      !- Name")
                if is_top:
                    self.add(f"  Roof,                    !- Surface Type")
                    self.add(f"  {const_prefix}_Roof,     !- Construction Name")
                    self.add(f"  {zone_name},              !- Zone Name")
                    self.add(f"  ,                         !- Space Name")
                    self.add(f"  Outdoors,                 !- Outside Boundary Condition")
                    self.add(f"  ,                         !- Outside Boundary Condition Object")
                    self.add(f"  SunExposed,               !- Sun Exposure")
                    self.add(f"  WindExposed,              !- Wind Exposure")
                else:
                    self.add(f"  Ceiling,                  !- Surface Type")
                    self.add(f"  InteriorFloor,            !- Construction Name")
                    self.add(f"  {zone_name},              !- Zone Name")
                    self.add(f"  ,                         !- Space Name")
                    self.add(f"  Adiabatic,                !- Outside Boundary Condition")
                    self.add(f"  ,                         !- Outside Boundary Condition Object")
                    self.add(f"  NoSun,                    !- Sun Exposure")
                    self.add(f"  NoWind,                   !- Wind Exposure")
                self.add(f"  ,                         !- View Factor to Ground")
                self.add(f"  {n_verts},                !- Number of Vertices")
                h = ceil_z_m - floor_z_m
                # Ceiling vertices (counterclockwise from above)
                for vi in range(n_verts - 1, -1, -1):
                    v = verts_m[vi]
                    comma = "," if vi > 0 else ";"
                    self.add(f"  {v[0]:.3f}, {v[1]:.3f}, {h:.3f}{comma}")
                self.add("")

                # Wall surfaces — one per edge
                for wi in range(n_verts):
                    v1 = verts_m[wi]
                    v2 = verts_m[(wi + 1) % n_verts]

                    # All perimeter walls are exterior
                    wall_name = f"{zone_name}_Wall_{wi+1}"
                    self.add(f"BuildingSurface:Detailed,")
                    self.add(f"  {wall_name},              !- Name")
                    self.add(f"  Wall,                     !- Surface Type")
                    self.add(f"  {const_prefix}_Wall,     !- Construction Name")
                    self.add(f"  {zone_name},              !- Zone Name")
                    self.add(f"  ,                         !- Space Name")
                    self.add(f"  Outdoors,                 !- Outside Boundary Condition")
                    self.add(f"  ,                         !- Outside Boundary Condition Object")
                    self.add(f"  SunExposed,               !- Sun Exposure")
                    self.add(f"  WindExposed,              !- Wind Exposure")
                    self.add(f"  ,                         !- View Factor to Ground")
                    self.add(f"  4,                        !- Number of Vertices")
                    self.add(f"  {v1[0]:.3f}, {v1[1]:.3f}, {h:.3f},")
                    self.add(f"  {v1[0]:.3f}, {v1[1]:.3f}, 0.000,")
                    self.add(f"  {v2[0]:.3f}, {v2[1]:.3f}, 0.000,")
                    self.add(f"  {v2[0]:.3f}, {v2[1]:.3f}, {h:.3f};")
                    self.add("")

            cum_height_ft += ftf

    def _add_fenestration(self):
        """Add windows based on WWR."""
        if not self.stories or not self.window_defs:
            return

        self.add_comment("--- Fenestration ---")
        self.add("")

        wwr = self.window_defs[0].get('wwr', 0.25)

        # Re-derive walls from the zone data to add windows
        cum_height_ft = 0.0
        for si, story in enumerate(self.stories):
            ftf = story.get('floor_to_floor', 10)
            ftc = story.get('floor_to_ceiling', 9)
            h = ft_to_m(ftc)

            for sp in story.get('spaces', []):
                space_name = sp.get('name', f'Space_{si}')
                zone_name = f"{space_name}".replace(' ', '_')
                verts = sp.get('vertices', [])
                verts_m = [[ft_to_m(v[0]), ft_to_m(v[1])] for v in verts]
                n_verts = len(verts_m)

                for wi in range(n_verts):
                    v1 = verts_m[wi]
                    v2 = verts_m[(wi + 1) % n_verts]
                    wall_name = f"{zone_name}_Wall_{wi+1}"

                    # Calculate wall width
                    wall_w = math.sqrt((v2[0]-v1[0])**2 + (v2[1]-v1[1])**2)
                    if wall_w < 1.0 or h < 1.0:
                        continue

                    # Window inset (0.5m from edges, 1m from floor, 0.3m from ceiling)
                    margin_h = 0.5
                    sill_h = 1.0
                    head_margin = 0.3
                    win_w = wall_w * math.sqrt(wwr)  # approximate
                    win_h = h * math.sqrt(wwr)
                    # Ensure reasonable dimensions
                    win_w = min(win_w, wall_w - 2 * margin_h)
                    win_h = min(win_h, h - sill_h - head_margin)
                    if win_w < 0.3 or win_h < 0.3:
                        continue

                    # Center the window horizontally
                    offset_h = (wall_w - win_w) / 2
                    # Direction vector along wall
                    dx = (v2[0] - v1[0]) / wall_w
                    dy = (v2[1] - v1[1]) / wall_w

                    # Window corners (4 vertices, from upper-left going clockwise from outside)
                    wx1 = v1[0] + dx * offset_h
                    wy1 = v1[1] + dy * offset_h
                    wx2 = v1[0] + dx * (offset_h + win_w)
                    wy2 = v1[1] + dy * (offset_h + win_w)

                    self.add(f"FenestrationSurface:Detailed,")
                    self.add(f"  {wall_name}_Win,         !- Name")
                    self.add(f"  Window,                  !- Surface Type")
                    self.add(f"  WindowConstruction,      !- Construction Name")
                    self.add(f"  {wall_name},              !- Building Surface Name")
                    self.add(f"  ,                         !- Outside Boundary Condition Object")
                    self.add(f"  ,                         !- View Factor to Ground")
                    self.add(f"  ,                         !- Frame and Divider Name")
                    self.add(f"  1,                        !- Multiplier")
                    self.add(f"  4,                        !- Number of Vertices")
                    self.add(f"  {wx1:.3f}, {wy1:.3f}, {sill_h + win_h:.3f},")
                    self.add(f"  {wx1:.3f}, {wy1:.3f}, {sill_h:.3f},")
                    self.add(f"  {wx2:.3f}, {wy2:.3f}, {sill_h:.3f},")
                    self.add(f"  {wx2:.3f}, {wy2:.3f}, {sill_h + win_h:.3f};")
                    self.add("")

            cum_height_ft += ftf

    def _add_internal_loads(self):
        """Add people, lights, equipment, and infiltration to each zone."""
        if not self.zone_names:
            return

        self.add_comment("--- Internal Loads ---")
        self.add("")

        # Building-type-specific internal loads (per ASHRAE 90.1-2016 / Appendix G)
        building_type = self.project.get("building_type", "office")

        # Equipment power density by building type (W/m²)
        EPD_BY_TYPE = {
            "office": 10.76,
            "retail": 10.76,
            "multi_unit_residential": 1.08,
            "multifamily": 1.08,
            "hotel": 5.38,
            "warehouse": 2.15,
            "school": 8.07,
            "hospital": 10.76
        }
        epd_w_m2 = EPD_BY_TYPE.get(building_type, 5.38)

        # People density by building type (people/m²)
        PEOPLE_BY_TYPE = {
            "office": 0.05,
            "retail": 0.15,
            "multi_unit_residential": 0.04,
            "multifamily": 0.04,
            "hotel": 0.06,
            "warehouse": 0.01,
            "school": 0.25,
            "hospital": 0.10
        }
        people_density = PEOPLE_BY_TYPE.get(building_type, 0.05)

        lpd = 1.0  # W/ft² existing, or use model value
        infil_ach = 0.5  # Air changes per hour

        for zone_name in self.zone_names:
            area = self.zone_floor_areas.get(zone_name, 100)

            # People
            num_people = max(1, area * people_density)
            self.add(f"People,")
            self.add(f"  {zone_name}_People,       !- Name")
            self.add(f"  {zone_name},              !- Zone Name")
            self.add(f"  ResOccupancy,            !- Number of People Schedule Name")
            self.add(f"  People,                  !- Number of People Calculation Method")
            self.add(f"  {num_people:.0f},          !- Number of People")
            self.add(f"  ,                         !- People per Floor Area")
            self.add(f"  ,                         !- Floor Area per Person")
            self.add(f"  0.3,                      !- Fraction Radiant")
            self.add(f"  autocalculate,            !- Sensible Heat Fraction")
            self.add(f"  ActivitySchedule;        !- Activity Level Schedule Name")
            self.add("")

            # Lights
            self.add(f"Lights,")
            self.add(f"  {zone_name}_Lights,       !- Name")
            self.add(f"  {zone_name},              !- Zone Name")
            self.add(f"  ResLighting,             !- Schedule Name")
            self.add(f"  Watts/Area,              !- Design Level Calculation Method")
            self.add(f"  ,                         !- Lighting Level")
            self.add(f"  {lpd * 10.7639:.2f},      !- Watts per Floor Area (W/m2)")
            self.add(f"  ,                         !- Watts per Person")
            self.add(f"  0,                        !- Return Air Fraction")
            self.add(f"  0.7,                      !- Fraction Radiant")
            self.add(f"  0.2;                      !- Fraction Visible")
            self.add("")

            # Equipment (plug loads)
            self.add(f"ElectricEquipment,")
            self.add(f"  {zone_name}_Equipment,    !- Name")
            self.add(f"  {zone_name},              !- Zone Name")
            self.add(f"  ResEquipment,            !- Schedule Name")
            self.add(f"  Watts/Area,              !- Design Level Calculation Method")
            self.add(f"  ,                         !- Design Level")
            self.add(f"  {epd_w_m2:.2f},           !- Watts per Floor Area (W/m2)")
            self.add(f"  ,                         !- Watts per Person")
            self.add(f"  0,                        !- Fraction Latent")
            self.add(f"  0.5,                      !- Fraction Radiant")
            self.add(f"  0;                        !- Fraction Lost")
            self.add("")

            # Infiltration
            self.add(f"ZoneInfiltration:DesignFlowRate,")
            self.add(f"  {zone_name}_Infiltration, !- Name")
            self.add(f"  {zone_name},              !- Zone Name")
            self.add(f"  Always On,               !- Schedule Name")
            self.add(f"  AirChanges/Hour,         !- Design Flow Rate Calculation Method")
            self.add(f"  ,                         !- Design Flow Rate")
            self.add(f"  ,                         !- Flow Rate per Floor Area")
            self.add(f"  ,                         !- Flow Rate per Exterior Surface Area")
            self.add(f"  {infil_ach},              !- Air Changes per Hour")
            self.add(f"  1,                        !- Constant Term Coefficient")
            self.add(f"  0,                        !- Temperature Term Coefficient")
            self.add(f"  0,                        !- Velocity Term Coefficient")
            self.add(f"  0;                        !- Velocity Squared Term Coefficient")
            self.add("")

    def _add_hvac(self):
        """Add HVAC using HVACTemplate:Zone:IdealLoadsAirSystem for reliable results."""
        if not self.zone_names:
            return

        self.add_comment("--- HVAC (Ideal Loads for Sizing) ---")
        self.add("")

        # Thermostat setpoint schedules - will be added in Task 20 (schedules)
        # For now, use placeholder that will be defined there

        # Thermostat
        self.add("ThermostatSetpoint:DualSetpoint,")
        self.add("  DualThermostat,          !- Name")
        self.add("  HtgSetpoint,             !- Heating Setpoint Temperature Schedule Name")
        self.add("  ClgSetpoint;             !- Cooling Setpoint Temperature Schedule Name")
        self.add("")

        for zone_name in self.zone_names:
            # Zone control thermostat
            self.add(f"ZoneControl:Thermostat,")
            self.add(f"  {zone_name}_Thermostat,   !- Name")
            self.add(f"  {zone_name},              !- Zone Name")
            self.add(f"  DualSetpointControlType, !- Control Type Schedule Name")
            self.add(f"  ThermostatSetpoint:DualSetpoint, !- Control 1 Object Type")
            self.add(f"  DualThermostat;          !- Control 1 Name")
            self.add("")

            # Ideal loads air system — captures all heating/cooling energy
            self.add(f"ZoneHVAC:IdealLoadsAirSystem,")
            self.add(f"  {zone_name}_IdealLoads,   !- Name")
            self.add(f"  Always On,               !- Availability Schedule Name")
            self.add(f"  {zone_name}_IdealLoads_SupplyNode, !- Zone Supply Air Node Name")
            self.add(f"  {zone_name}_IdealLoads_ExhaustNode, !- Zone Exhaust Air Node Name")
            self.add(f"  ,                         !- System Inlet Air Node Name")
            self.add(f"  50,                       !- Maximum Heating Supply Air Temperature (C)")
            self.add(f"  13,                       !- Minimum Cooling Supply Air Temperature (C)")
            self.add(f"  0.0156,                   !- Maximum Heating Supply Air Humidity Ratio (kgWater/kgDryAir)")
            self.add(f"  0.0077,                   !- Minimum Cooling Supply Air Humidity Ratio (kgWater/kgDryAir)")
            self.add(f"  NoLimit,                  !- Heating Limit")
            self.add(f"  ,                         !- Maximum Heating Air Flow Rate")
            self.add(f"  ,                         !- Maximum Sensible Heating Capacity")
            self.add(f"  NoLimit,                  !- Cooling Limit")
            self.add(f"  ,                         !- Maximum Cooling Air Flow Rate")
            self.add(f"  ,                         !- Maximum Total Cooling Capacity")
            self.add(f"  ,                         !- Heating Availability Schedule Name")
            self.add(f"  ,                         !- Cooling Availability Schedule Name")
            self.add(f"  ConstantSensibleHeatRatio, !- Dehumidification Control Type")
            self.add(f"  0.7,                      !- Cooling Sensible Heat Ratio")
            self.add(f"  None,                     !- Humidification Control Type")
            self.add(f"  ,                         !- Design Specification Outdoor Air Object Name")
            self.add(f"  ,                         !- Outdoor Air Inlet Node Name")
            self.add(f"  None,                     !- Demand Controlled Ventilation Type")
            self.add(f"  NoEconomizer,             !- Outdoor Air Economizer Type")
            self.add(f"  None,                     !- Heat Recovery Type")
            self.add(f"  0.7,                      !- Sensible Heat Recovery Effectiveness")
            self.add(f"  0.65;                     !- Latent Heat Recovery Effectiveness")
            self.add("")

            # Zone equipment list
            self.add(f"ZoneHVAC:EquipmentList,")
            self.add(f"  {zone_name}_EquipList,    !- Name")
            self.add(f"  SequentialLoad,           !- Load Distribution Scheme")
            self.add(f"  ZoneHVAC:IdealLoadsAirSystem, !- Zone Equipment 1 Object Type")
            self.add(f"  {zone_name}_IdealLoads,   !- Zone Equipment 1 Name")
            self.add(f"  1,                        !- Zone Equipment 1 Cooling Sequence")
            self.add(f"  1;                        !- Zone Equipment 1 Heating or No-Load Sequence")
            self.add("")

            self.add(f"ZoneHVAC:EquipmentConnections,")
            self.add(f"  {zone_name},              !- Zone Name")
            self.add(f"  {zone_name}_EquipList,    !- Zone Conditioning Equipment List Name")
            self.add(f"  {zone_name}_SupplyNodes,  !- Zone Air Inlet Node or NodeList Name")
            self.add(f"  {zone_name}_ExhaustNodes, !- Zone Air Exhaust Node or NodeList Name")
            self.add(f"  {zone_name}_AirNode,      !- Zone Air Node Name")
            self.add(f"  {zone_name}_ReturnNode;   !- Zone Return Air Node or NodeList Name")
            self.add("")

            self.add(f"NodeList,")
            self.add(f"  {zone_name}_SupplyNodes,  !- Name")
            self.add(f"  {zone_name}_IdealLoads_SupplyNode; !- Node 1 Name")
            self.add("")

            self.add(f"NodeList,")
            self.add(f"  {zone_name}_ExhaustNodes, !- Name")
            self.add(f"  {zone_name}_IdealLoads_ExhaustNode; !- Node 1 Name")
            self.add("")

    def _add_output_variables(self):
        """Add output variables for post-processing."""
        self.add_comment("--- Output Variables ---")
        self.add("")
        self.add("Output:Table:SummaryReports,")
        self.add("  AllSummary;              !- Report 1 Name")
        self.add("")
        self.add("OutputControl:Table:Style,")
        self.add("  HTML;                    !- Column Separator")
        self.add("")
        self.add("Output:SQLite,")
        self.add("  SimpleAndTabular;        !- Option Type")
        self.add("")
        # Key meters for EUI calculation
        self.add("Output:Meter,Electricity:Facility,Monthly;")
        self.add("Output:Meter,NaturalGas:Facility,Monthly;")
        self.add("Output:Meter,DistrictHeating:Facility,Monthly;")
        self.add("Output:Meter,DistrictCooling:Facility,Monthly;")
        self.add("")
        # End-use breakdown
        self.add("Output:Meter,Heating:EnergyTransfer,Monthly;")
        self.add("Output:Meter,Cooling:EnergyTransfer,Monthly;")
        self.add("")
        # Unmet hours
        self.add("Output:Variable,*,Zone Ideal Loads Heating Energy,Monthly;")
        self.add("Output:Variable,*,Zone Ideal Loads Cooling Energy,Monthly;")
        self.add("Output:Variable,*,Zone Mean Air Temperature,Monthly;")
        self.add("")

    @staticmethod
    def _polygon_area(vertices: List[List[float]]) -> float:
        """Calculate polygon area using shoelace formula. Returns area in same units as vertices (ft²)."""
        n = len(vertices)
        if n < 3:
            return 0
        area = 0
        for i in range(n):
            j = (i + 1) % n
            area += vertices[i][0] * vertices[j][1]
            area -= vertices[j][0] * vertices[i][1]
        return abs(area) / 2


def apply_ashrae_901_2022(building_model: Dict[str, Any]) -> Dict[str, Any]:
    """
    Apply ASHRAE 90.1-2022 prescriptive requirements to building model.

    Modifies envelope R-values, window U-factor/SHGC, lighting LPD, and
    HVAC efficiency parameters based on climate zone.

    Args:
        building_model: Building model dict with geometry.climate_zone

    Returns:
        Updated building model dict with 90.1-2022 parameters applied
    """
    # Deep copy to avoid mutating original
    updated = copy.deepcopy(building_model)

    # Get climate zone
    climate_zone = updated.get('geometry', {}).get('climate_zone', '5A')

    # Load ASHRAE 90.1-2022 data
    data_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'ashrae_901_2022.json')
    with open(data_path, 'r') as f:
        ashrae_data = json.load(f)

    # Get requirements for climate zone
    if climate_zone not in ashrae_data['climate_zones']:
        # Default to 5A if climate zone not found
        climate_zone = '5A'

    requirements = ashrae_data['climate_zones'][climate_zone]

    # Apply envelope parameters
    if 'envelope' not in updated:
        updated['envelope'] = {}

    envelope_params = requirements.get('envelope', {})
    updated['envelope']['wall_r_value'] = envelope_params.get('wall_r_value', updated['envelope'].get('wall_r_value', 13.0))
    updated['envelope']['wall_ci_r_value'] = envelope_params.get('wall_ci_r_value', updated['envelope'].get('wall_ci_r_value', 0))
    updated['envelope']['roof_r_value'] = envelope_params.get('roof_r_value', updated['envelope'].get('roof_r_value', 20.0))
    updated['envelope']['slab_r_value'] = envelope_params.get('slab_r_value', updated['envelope'].get('slab_r_value', 0))
    updated['envelope']['window_u_factor'] = envelope_params.get('window_u_factor', updated['envelope'].get('window_u_factor', 0.42))
    updated['envelope']['window_shgc'] = envelope_params.get('window_shgc', updated['envelope'].get('window_shgc', 0.40))

    # Apply lighting parameters based on building type
    building_type = updated.get('geometry', {}).get('building_type', 'office').lower()
    if 'lighting' not in updated:
        updated['lighting'] = {}

    lighting_params = requirements.get('lighting', {})
    if 'multifamily' in building_type or 'residential' in building_type:
        lpd = lighting_params.get('multifamily_lpd', 0.60)
    elif 'retail' in building_type:
        lpd = lighting_params.get('retail_lpd', 0.90)
    elif 'warehouse' in building_type:
        lpd = lighting_params.get('warehouse_lpd', 0.40)
    else:  # office or other
        lpd = lighting_params.get('office_lpd', 0.60)

    updated['lighting']['lpd'] = lpd

    # Apply systems parameters
    if 'systems' not in updated:
        updated['systems'] = {}

    systems_params = requirements.get('systems', {})
    updated['systems']['heating_cop'] = systems_params.get('heating_cop_min', updated['systems'].get('heating_cop', 3.0))
    updated['systems']['cooling_eer'] = systems_params.get('cooling_eer_min', updated['systems'].get('cooling_eer', 12.0))
    updated['systems']['boiler_eff'] = systems_params.get('boiler_eff_min', updated['systems'].get('boiler_eff', 0.80))
    updated['systems']['dhw_eff'] = systems_params.get('dhw_eff_min', updated['systems'].get('dhw_eff', 0.80))

    # Apply ventilation parameters
    if 'ventilation' not in updated:
        updated['ventilation'] = {}

    ventilation_params = requirements.get('ventilation', {})
    updated['ventilation']['cfm_per_person'] = ventilation_params.get('cfm_per_person', updated['ventilation'].get('cfm_per_person', 7.5))
    updated['ventilation']['cfm_per_sqft'] = ventilation_params.get('cfm_per_sqft', updated['ventilation'].get('cfm_per_sqft', 0.06))

    return updated


def generate_idf(payload: Dict[str, Any]) -> str:
    """
    Main entry point: takes building model payload, returns IDF string.

    Args:
        payload: Building model dict (see IDFGenerator.__init__ for structure)

    Returns:
        Complete IDF file content as string
    """
    gen = IDFGenerator(payload)
    return gen.generate()


def validate_idf(idf_content: str) -> tuple[bool, List[str]]:
    """
    Validate IDF content for required sections and basic syntax.

    Args:
        idf_content: IDF file content as string

    Returns:
        Tuple of (is_valid, error_messages)
    """
    errors = []

    # Required objects for a valid IDF
    required_objects = [
        'Version',
        'Building',
        'SimulationControl',
        'RunPeriod',
        'Timestep'
    ]

    # Check for required objects
    for obj in required_objects:
        if f'{obj},' not in idf_content:
            errors.append(f"Missing required object: {obj}")

    # Check for basic syntax errors
    lines = idf_content.split('\n')
    in_object = False
    for i, line in enumerate(lines):
        stripped = line.strip()
        if not stripped or stripped.startswith('!'):
            continue

        # Check for object start (ends with comma)
        if ',' in stripped and not in_object:
            # Could be object name or field
            if stripped.endswith(','):
                in_object = True

        # Check for object end (ends with semicolon)
        if ';' in stripped:
            in_object = False

    # If still in object at end, that's an error
    if in_object:
        errors.append("IDF has unclosed object (missing semicolon)")

    is_valid = len(errors) == 0
    return (is_valid, errors)


def write_idf(idf_content: str, output_dir: str, building_name: str, scenario: str = 'baseline') -> str:
    """
    Write IDF content to file with proper naming convention.

    Args:
        idf_content: IDF file content as string
        output_dir: Directory to write IDF file
        building_name: Building name for filename
        scenario: Scenario name (baseline, 90.1-2022, retrofit, etc.)

    Returns:
        Path to written IDF file
    """
    # Sanitize building name for filename
    safe_building_name = building_name.replace(' ', '_').replace('/', '_').replace('\\', '_')
    safe_scenario = scenario.replace(' ', '_').replace('/', '_').replace('\\', '_')

    # Construct filename
    filename = f"{safe_building_name}_{safe_scenario}.idf"
    file_path = os.path.join(output_dir, filename)

    # Write IDF content
    with open(file_path, 'w') as f:
        f.write(idf_content)

    return file_path
